create  table  if not exists  HUB_CIRCUITS
(
CIRCUIT_ID_BK VARCHAR(500),
CIRCUIT_ID_HK VARCHAR(500),
LOAD_DATE DATE,
RECORD_SOURCE VARCHAR(1000),
constraint  CIRCUIT_ID_HK_PK PRIMARY KEY  (CIRCUIT_ID_HK)
);


create  table  if not exists  HUB_CONSTRUCTOR
(
CONSTUCTOR_BK VARCHAR(500),
CONSTUCTOR_HK VARCHAR(500),
LOAD_DATE DATE,
RECORD_SOURCE VARCHAR(1000),
constraint  CONSTUCTOR_HK_PK PRIMARY KEY  (CONSTUCTOR_HK)
);


create  table  if not exists  HUB_DRIVERS
(
DRIVER_ID_BK VARCHAR(500),
DRIVER_ID_HK VARCHAR(500),
LOAD_DATE DATE,
RECORD_SOURCE VARCHAR(1000),
constraint  DRIVER_ID_HK_PK PRIMARY KEY  (DRIVER_ID_HK)
);



create  table  if not exists  HUB_RACES
(
RACE_ID_BK VARCHAR(500),
RACE_ID_HK VARCHAR(500),
LOAD_DATE DATE,
RECORD_SOURCE VARCHAR(1000)
constraint  RACE_ID_HK_PK PRIMARY KEY  (RACE_ID_HK)
);

create  table  if not exists  HUB_STATUS
(
STATUS_ID_BK VARCHAR(500),
STATUS_ID_HK VARCHAR(500),
LOAD_DATE DATE,
RECORD_SOURCE VARCHAR(1000),
constraint  STATUS_ID_HK_PK PRIMARY KEY  (STATUS_ID_HK)
);


create  table  if not exists  LNK_CIRCUITS_CONSTRUCTOR
(
CIRCUIT_ID_HK VARCHAR(500), 
CONSTUCTOR_HK VARCHAR(500),
CIRC_CONS_HK VARCHAR(500),
LOAD_DATE DATE,
RECORD_SOURCE VARCHAR(1000),
constraint  CIRC_CONS_HK_PK PRIMARY KEY  (CIRC_CONS_HK)
);

create  table  if not exists LNK_RESULTS
(
CONSTUCTOR_HK  VARCHAR(500),
RACE_ID_HK VARCHAR(500),
DRIVER_ID_HK VARCHAR(500),
STATUS_ID_HK VARCHAR(500), 
RESULT_ID_HKVARCHAR(500),
CONS_RES_DRIV_STAT_HK VARCHAR(500),
LOAD_DATE DATE ,
RECORD_SOURCE VARCHAR(1000),
constraint  CONS_RES_DRIV_STAT_HK_PK PRIMARY KEY  (CONS_RES_DRIV_STAT_HK)
);

create  table  if not exists SAT_RACEs
LOAD_DATE DATE ,
RECORD_SOURCE VARCHAR(1000),
RACE_HASH_DIFF VARCHAR(500),
RACE_HK VARCHAR(500),
YEAR INTEGER,
ROUND   INTEGER,
CIRCUITID  INTEGER,
NAME  VARCHAR(500),
DATE  DATE ,
TIME  TIME ,
URL  VARCHAR(500),
constraint  RACE_HASH_DIFF_PK PRIMARY KEY  (RACE_HASH_DIFF)
);

create  table  if not exists SAT_CIRCUITS
(LOAD_DATE DATE,
RECORD_SOURCE  VARCHAR(1000),
CIRCUITS_HASH_DIFF VARCHAR(500),
CIRCUITS_HASH_KEY VARCHAR(500),
CIRCUITREF  VARCHAR(500),
NAME  VARCHAR(500),
LOCATION  VARCHAR(500),
COUNTRY  VARCHAR(500),
LAT  FLOAT,
LNG  FLOAT,
ALT INTEGER,
URL VARCHAR(500),
 constraint  CIRCUITS_HASH_DIFF_PK PRIMARY KEY  (CIRCUITS_HASH_DIFF)
 );


create  table  if not exists SAT_CONSTRUCTOR
(LOAD_DATE DATE ,
RECORD_SOURCE VARCHAR(1000),
CONSTUCTOR_HK VARCHAR(500),
CONSTUCTOR_HASH_DIFF VARCHAR(500)
CONSTRUCTORREF  VARCHAR(500), 
NAME  VARCHAR(500),
NATIONALITY  VARCHAR(500),
URL VARCHAR(500),
constraint  CONSTUCTOR_HASH_DIFF_PK PRIMARY KEY  (CONSTUCTOR_HASH_DIFF) 
 );


create  table  if not exists SAT_DRIVERS
(LOAD_DATE DATE,
RECORD_SOURCE  VARCHAR(1000),
DRIVER_ID_HK VARCHAR(500),
DRIVER_HASH_DIFF VARCHAR(500),
DRIVERREF  VARCHAR(500),
NUMBER  INTEGER,
CODE  VARCHAR(500),
FORENAME  VARCHAR(500),
SURNAME  VARCHAR(500),
DOB  DATE ,
NATIONALITY VARCHAR(500), 
URL  VARCHAR(500),
 constraint  DRIVER_HASH_DIFF_PK PRIMARY KEY  (DRIVER_HASH_DIFF) 
);


create  table  if not exists SAT_STATUS
(LOAD_DATE DATE ,
RECORD_SOURCE VARCHAR(1000),
STATUS_HK VARCHAR(500),
STATUS_HASH_DIFF VARCHAR(500),
STATUS VARCHAR(500),
 constraint  STATUS_HASH_DIFF_PK PRIMARY KEY  (STATUS_HASH_DIFF)
); 

create  table  if not exists SAT_LNK_RESULTS
(LOAD_DATE DATE ,
RECORD_SOURCE VARCHAR(1000),
CONS_RES_DRIV_STAT_HK  VARCHAR(500),
RESULTS_HASH_DIFF VARCHAR(500),
NUMBER INTEGER,
GRID  INTEGER,
POSITION  INTEGER,
POSITIONTEXT  VARCHAR(500),
POSITIONORDER  INTEGER,
POINTS FLOAT,
LAPS  INTEGER,
TIME   TIME,
MILLISECONDS INTEGER ,
FASTESTLAP  TIME,
RANK   INTEGER,
FASTESTLAPTIME TIME,
FASTESTLAPSPEED  FLOAT,
 constraint  RESULTS_HASH_DIFF_PK PRIMARY KEY  (RESULTS_HASH_DIFF)
);

